const FPS = 60;
const LINES_WIDTH = 1;
const GAME_LIVES = 3; // starting number of lives
const FRICTION = 0.7;
const ROIDS_NUM = 5; // starting number of asteroids
const ROIDS_SIZE = 100; // starting size in px
const ROIDS_SPD = 70; // max starting speed 
const ROIDS_VERT = 10; // average number of vertices 
const ROIDS_JAG = 0.35; // jaggedness (0 = none, 1 = lots)
const ROIDS_EXPL_PIECES = 25; // number of pieces when the roids breaks
const ROIDS_EXPL_TIME = 0.65; // sec
const ROIDS_EXPL_RADIUS = ROIDS_SIZE / 4 * 0.5;
const ROIDS_PTS_LGE = 20; // point scored when destroing large asteroids
const ROIDS_PTS_MED = 50; // point scored when destroing medium asteroids
const ROIDS_PTS_SML = 100; // point scored when destroing small asteroids
const SHIP_SIZE = 20; // height in px
const SHIP_THRUST = 3.5; // accelleration
const SHIP_EXPL_DUR = 1.5; // exploding animation in sec
const SHIP_EXPL_RADIUS = SHIP_SIZE * 1.2;
const SHIP_EXPL_ANIM = "A2"; // choose animation "A1" or "A2" 
const SHIP_INV_DUR = 3; // ship invulnerability when respawning in sec
const SHIP_BLINK_DUR = 0.2; // duration of one blink in sec
const SHIP_TURN_SPEED = 1.3 * Math.PI; // rad per sec
const PROJ_MAX = 10; // maximum number of projectiles on screen at once
const PROJ_SPEED = 550; // speed of projectiles 
const PROJ_MAX_DIST = 0.6; // maximum distance a proj can travel as fraction of screen width
const TEXT_FADE_TIME = 2.5; //text fade time is sec
const TEXT_SIZE = 35; //text font height in px
const SHOW_COLLISION_CIRCLES = false;
